// Mocks generated by Mockito 5.4.6 from annotations
// in litstop/test/providers/poi_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:google_maps_flutter/google_maps_flutter.dart' as _i6;
import 'package:litstop/models/gas_station.dart' as _i9;
import 'package:litstop/models/poi_filter.dart' as _i7;
import 'package:litstop/models/point_of_interest.dart' as _i5;
import 'package:litstop/services/gas_price_service.dart' as _i8;
import 'package:litstop/services/poi_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [POIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPOIService extends _i1.Mock implements _i2.POIService {
  MockPOIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  Map<String, String> get defaultHeaders => (super.noSuchMethod(
        Invocation.getter(#defaultHeaders),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  Duration get timeout => (super.noSuchMethod(
        Invocation.getter(#timeout),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#timeout),
        ),
      ) as Duration);

  @override
  _i4.Future<List<_i5.PointOfInterest>> fetchNearbyPOIs({
    required _i6.LatLng? location,
    required List<_i5.POIType>? poiTypes,
    int? radius = 5000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchNearbyPOIs,
          [],
          {
            #location: location,
            #poiTypes: poiTypes,
            #radius: radius,
          },
        ),
        returnValue: _i4.Future<List<_i5.PointOfInterest>>.value(
            <_i5.PointOfInterest>[]),
      ) as _i4.Future<List<_i5.PointOfInterest>>);

  @override
  _i4.Future<List<_i5.PointOfInterest>> searchPOIs({
    required String? query,
    required _i6.LatLng? location,
    int? radius = 5000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPOIs,
          [],
          {
            #query: query,
            #location: location,
            #radius: radius,
          },
        ),
        returnValue: _i4.Future<List<_i5.PointOfInterest>>.value(
            <_i5.PointOfInterest>[]),
      ) as _i4.Future<List<_i5.PointOfInterest>>);

  @override
  _i4.Future<List<_i6.LatLng>> calculateRoute({
    required _i6.LatLng? start,
    required _i6.LatLng? end,
    List<_i6.LatLng>? waypoints,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateRoute,
          [],
          {
            #start: start,
            #end: end,
            #waypoints: waypoints,
          },
        ),
        returnValue: _i4.Future<List<_i6.LatLng>>.value(<_i6.LatLng>[]),
      ) as _i4.Future<List<_i6.LatLng>>);

  @override
  _i4.Future<List<_i5.PointOfInterest>> getPOIsAlongRoute({
    required List<_i6.LatLng>? routePoints,
    required List<_i5.POIType>? poiTypes,
    int? bufferDistance = 1000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPOIsAlongRoute,
          [],
          {
            #routePoints: routePoints,
            #poiTypes: poiTypes,
            #bufferDistance: bufferDistance,
          },
        ),
        returnValue: _i4.Future<List<_i5.PointOfInterest>>.value(
            <_i5.PointOfInterest>[]),
      ) as _i4.Future<List<_i5.PointOfInterest>>);

  @override
  _i4.Future<List<_i5.PointOfInterest>> findRestAreasAlongRoute({
    required _i6.LatLng? start,
    required _i6.LatLng? end,
    int? bufferDistance = 1000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findRestAreasAlongRoute,
          [],
          {
            #start: start,
            #end: end,
            #bufferDistance: bufferDistance,
          },
        ),
        returnValue: _i4.Future<List<_i5.PointOfInterest>>.value(
            <_i5.PointOfInterest>[]),
      ) as _i4.Future<List<_i5.PointOfInterest>>);

  @override
  _i4.Future<List<_i5.PointOfInterest>> findGasStationsAlongRoute({
    required _i6.LatLng? start,
    required _i6.LatLng? end,
    int? bufferDistance = 1000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findGasStationsAlongRoute,
          [],
          {
            #start: start,
            #end: end,
            #bufferDistance: bufferDistance,
          },
        ),
        returnValue: _i4.Future<List<_i5.PointOfInterest>>.value(
            <_i5.PointOfInterest>[]),
      ) as _i4.Future<List<_i5.PointOfInterest>>);

  @override
  _i4.Future<List<_i5.PointOfInterest>> findFoodAlongRoute({
    required _i6.LatLng? start,
    required _i6.LatLng? end,
    int? bufferDistance = 1000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findFoodAlongRoute,
          [],
          {
            #start: start,
            #end: end,
            #bufferDistance: bufferDistance,
          },
        ),
        returnValue: _i4.Future<List<_i5.PointOfInterest>>.value(
            <_i5.PointOfInterest>[]),
      ) as _i4.Future<List<_i5.PointOfInterest>>);

  @override
  List<_i5.PointOfInterest> applyFilter(
    List<_i5.PointOfInterest>? pois,
    _i7.POIFilter? filter,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyFilter,
          [
            pois,
            filter,
          ],
        ),
        returnValue: <_i5.PointOfInterest>[],
      ) as List<_i5.PointOfInterest>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<Map<String, dynamic>> get(
    String? endpoint, {
    Map<String, String>? headers,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {
            #headers: headers,
            #queryParameters: queryParameters,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> post(
    String? endpoint, {
    Map<String, String>? headers,
    Map<String, dynamic>? queryParameters,
    Object? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [endpoint],
          {
            #headers: headers,
            #queryParameters: queryParameters,
            #body: body,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [GasPriceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGasPriceService extends _i1.Mock implements _i8.GasPriceService {
  MockGasPriceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  Map<String, String> get defaultHeaders => (super.noSuchMethod(
        Invocation.getter(#defaultHeaders),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  Duration get timeout => (super.noSuchMethod(
        Invocation.getter(#timeout),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#timeout),
        ),
      ) as Duration);

  @override
  void setCurrentState(String? state) => super.noSuchMethod(
        Invocation.method(
          #setCurrentState,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<List<_i9.GasStation>> getGasPrices() => (super.noSuchMethod(
        Invocation.method(
          #getGasPrices,
          [],
        ),
        returnValue: _i4.Future<List<_i9.GasStation>>.value(<_i9.GasStation>[]),
      ) as _i4.Future<List<_i9.GasStation>>);

  @override
  _i4.Future<List<_i9.GasStation>> getMultiStateGasPrices(
          List<String>? states) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMultiStateGasPrices,
          [states],
        ),
        returnValue: _i4.Future<List<_i9.GasStation>>.value(<_i9.GasStation>[]),
      ) as _i4.Future<List<_i9.GasStation>>);

  @override
  _i4.Future<List<_i9.GasStation>> getMetroAreaGasPrices() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMetroAreaGasPrices,
          [],
        ),
        returnValue: _i4.Future<List<_i9.GasStation>>.value(<_i9.GasStation>[]),
      ) as _i4.Future<List<_i9.GasStation>>);

  @override
  _i4.Future<List<_i9.GasStation>> getNearbyGasStations(
    _i6.LatLng? location, {
    double? radius = 5.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNearbyGasStations,
          [location],
          {#radius: radius},
        ),
        returnValue: _i4.Future<List<_i9.GasStation>>.value(<_i9.GasStation>[]),
      ) as _i4.Future<List<_i9.GasStation>>);

  @override
  _i4.Future<_i9.GasStation?> getGasStationDetails(String? stationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGasStationDetails,
          [stationId],
        ),
        returnValue: _i4.Future<_i9.GasStation?>.value(),
      ) as _i4.Future<_i9.GasStation?>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<Map<String, dynamic>> get(
    String? endpoint, {
    Map<String, String>? headers,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {
            #headers: headers,
            #queryParameters: queryParameters,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> post(
    String? endpoint, {
    Map<String, String>? headers,
    Map<String, dynamic>? queryParameters,
    Object? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [endpoint],
          {
            #headers: headers,
            #queryParameters: queryParameters,
            #body: body,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}
